
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Nov 22 2024 16:14:00 MST (Nov 22 2024 23:14:00 UTC)

// Verification Directory fv/Matrix_Multiplier 

module Matrix_Multiplier(matrix_A, matrix_B, clock, start, reset,
     matrix_result, matrix_count);
  input [11:0] matrix_A, matrix_B;
  input clock, start, reset;
  output [23:0] matrix_result;
  output [3:0] matrix_count;
  wire [11:0] matrix_A, matrix_B;
  wire clock, start, reset;
  wire [23:0] matrix_result;
  wire [3:0] matrix_count;
  wire [47:0] regfile_contents;
  wire [2:0] element_A;
  wire [2:0] element_B;
  wire [1:0] fsm_current_state;
  wire [3:0] AB_entries;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_282, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_292, n_293, n_294, n_295;
  wire n_296, n_297, n_298, n_300;
  DFFQSRX1 \regfile_contents_reg[4] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_292), .Q (regfile_contents[4]));
  DFFQSRX1 \regfile_contents_reg[16] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_297), .Q (regfile_contents[16]));
  DFFQSRX1 \regfile_contents_reg[22] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_290), .Q (regfile_contents[22]));
  DFFQSRX1 \regfile_contents_reg[28] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_298), .Q (regfile_contents[28]));
  DFFQSRX1 \regfile_contents_reg[34] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_294), .Q (regfile_contents[34]));
  DFFQSRX1 \regfile_contents_reg[10] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_293), .Q (regfile_contents[10]));
  DFFQSRX1 \regfile_contents_reg[40] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_295), .Q (regfile_contents[40]));
  DFFQSRX1 \regfile_contents_reg[46] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_291), .Q (regfile_contents[46]));
  MUX2X1 g3919__2398(.A (regfile_contents[28]), .B (n_296), .S (n_281),
       .Z (n_298));
  MUX2X1 g3918__5107(.A (n_296), .B (regfile_contents[16]), .S (n_275),
       .Z (n_297));
  MUX2X1 g3917__6260(.A (n_296), .B (regfile_contents[40]), .S (n_273),
       .Z (n_295));
  MUX2X1 g3916__4319(.A (n_296), .B (regfile_contents[34]), .S (n_283),
       .Z (n_294));
  DFFQSRX1 \regfile_contents_reg[41] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_274), .Q (regfile_contents[41]));
  DFFQSRX1 \regfile_contents_reg[23] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_278), .Q (regfile_contents[23]));
  DFFQSRX1 \regfile_contents_reg[29] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_282), .Q (regfile_contents[29]));
  DFFQSRX1 \regfile_contents_reg[35] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_284), .Q (regfile_contents[35]));
  MUX2X1 g3914__8428(.A (n_296), .B (regfile_contents[10]), .S (n_279),
       .Z (n_293));
  MUX2X1 g3921__5526(.A (regfile_contents[4]), .B (n_296), .S (n_285),
       .Z (n_292));
  MUX2X1 g3920__6783(.A (regfile_contents[46]), .B (n_296), .S (n_288),
       .Z (n_291));
  MUX2X1 g3915__3680(.A (n_296), .B (regfile_contents[22]), .S (n_277),
       .Z (n_290));
  DFFQSRX1 \regfile_contents_reg[17] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_276), .Q (regfile_contents[17]));
  DFFQSRX1 \regfile_contents_reg[11] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_280), .Q (regfile_contents[11]));
  DFFQSRX1 \regfile_contents_reg[47] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_289), .Q (regfile_contents[47]));
  DFFQSRX1 \regfile_contents_reg[5] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_287), .Q (regfile_contents[5]));
  DFFQSRX1 \regfile_contents_reg[21] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_265), .Q (regfile_contents[21]));
  DFFQSRX1 \regfile_contents_reg[15] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_271), .Q (regfile_contents[15]));
  DFFQSRX1 \regfile_contents_reg[3] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_266), .Q (regfile_contents[3]));
  DFFQSRX1 \regfile_contents_reg[27] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_272), .Q (regfile_contents[27]));
  DFFQSRX1 \regfile_contents_reg[9] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_267), .Q (regfile_contents[9]));
  DFFQSRX1 \regfile_contents_reg[39] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_264), .Q (regfile_contents[39]));
  DFFQSRX1 \regfile_contents_reg[33] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_268), .Q (regfile_contents[33]));
  DFFQSRX1 \regfile_contents_reg[45] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_269), .Q (regfile_contents[45]));
  MUX2X1 g3936__1617(.A (regfile_contents[47]), .B (n_286), .S (n_288),
       .Z (n_289));
  MUX2X1 g3935__2802(.A (regfile_contents[5]), .B (n_286), .S (n_285),
       .Z (n_287));
  MUX2X1 g3934__1705(.A (n_286), .B (regfile_contents[35]), .S (n_283),
       .Z (n_284));
  MUX2X1 g3937__5122(.A (regfile_contents[29]), .B (n_286), .S (n_281),
       .Z (n_282));
  MUX2X1 g3940__8246(.A (n_286), .B (regfile_contents[11]), .S (n_279),
       .Z (n_280));
  MUX2X1 g3939__7098(.A (n_286), .B (regfile_contents[23]), .S (n_277),
       .Z (n_278));
  MUX2X1 g3938__6131(.A (n_286), .B (regfile_contents[17]), .S (n_275),
       .Z (n_276));
  MUX2X1 g3941__1881(.A (n_286), .B (regfile_contents[41]), .S (n_273),
       .Z (n_274));
  MUX2X1 g3957__5115(.A (regfile_contents[27]), .B (n_270), .S (n_281),
       .Z (n_272));
  MUX2X1 g3956__7482(.A (n_270), .B (regfile_contents[15]), .S (n_275),
       .Z (n_271));
  MUX2X1 g3958__4733(.A (regfile_contents[45]), .B (n_270), .S (n_288),
       .Z (n_269));
  OR2X1 g3953__6161(.A (n_263), .B (n_286), .Z (n_296));
  MUX2X1 g3946__9315(.A (n_270), .B (regfile_contents[33]), .S (n_283),
       .Z (n_268));
  MUX2X1 g3962__9945(.A (n_270), .B (regfile_contents[9]), .S (n_279),
       .Z (n_267));
  MUX2X1 g3959__2883(.A (regfile_contents[3]), .B (n_270), .S (n_285),
       .Z (n_266));
  MUX2X1 g3948__2346(.A (n_270), .B (regfile_contents[21]), .S (n_277),
       .Z (n_265));
  MUX2X1 g3952__1666(.A (n_270), .B (regfile_contents[39]), .S (n_273),
       .Z (n_264));
  DFFQSRX1 \regfile_contents_reg[2] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_257), .Q (regfile_contents[2]));
  DFFQSRX1 \regfile_contents_reg[26] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_260), .Q (regfile_contents[26]));
  DFFQSRX1 \regfile_contents_reg[20] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_254), .Q (regfile_contents[20]));
  DFFQSRX1 \regfile_contents_reg[32] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_255), .Q (regfile_contents[32]));
  DFFQSRX1 \regfile_contents_reg[14] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_259), .Q (regfile_contents[14]));
  DFFQSRX1 \regfile_contents_reg[44] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_256), .Q (regfile_contents[44]));
  DFFQSRX1 \regfile_contents_reg[38] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_253), .Q (regfile_contents[38]));
  DFFQSRX1 \regfile_contents_reg[8] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_252), .Q (regfile_contents[8]));
  NOR2X1 g3963__7410(.A (n_261), .B (n_262), .Z (n_263));
  AND2X1 g3964__6417(.A (n_262), .B (n_261), .Z (n_286));
  MUX2X1 g3960__5477(.A (regfile_contents[26]), .B (n_258), .S (n_281),
       .Z (n_260));
  MUX2X1 g3955__2398(.A (n_258), .B (regfile_contents[14]), .S (n_275),
       .Z (n_259));
  MUX2X1 g3954__5107(.A (regfile_contents[2]), .B (n_258), .S (n_285),
       .Z (n_257));
  MUX2X1 g3961__6260(.A (regfile_contents[44]), .B (n_258), .S (n_288),
       .Z (n_256));
  MUX2X1 g3949__4319(.A (n_258), .B (regfile_contents[32]), .S (n_283),
       .Z (n_255));
  MUX2X1 g3947__8428(.A (n_258), .B (regfile_contents[20]), .S (n_277),
       .Z (n_254));
  MUX2X1 g3951__5526(.A (n_258), .B (regfile_contents[38]), .S (n_273),
       .Z (n_253));
  MUX2X1 g3950__6783(.A (n_258), .B (regfile_contents[8]), .S (n_279),
       .Z (n_252));
  XOR2X1 g3967__3680(.A (n_249), .B (n_250), .Z (n_270));
  NOR2X1 g3965__1617(.A (n_247), .B (n_251), .Z (n_262));
  NOR2X1 g3974__2802(.A (n_248), .B (n_250), .Z (n_251));
  DFFQSRX1 \regfile_contents_reg[19] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_246), .Q (regfile_contents[19]));
  DFFQSRX1 \regfile_contents_reg[25] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_239), .Q (regfile_contents[25]));
  DFFQSRX1 \regfile_contents_reg[1] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_237), .Q (regfile_contents[1]));
  XOR2X1 g3966__1705(.A (n_234), .B (n_233), .Z (n_258));
  OR2X1 g3986__5122(.A (n_248), .B (n_247), .Z (n_249));
  DFFQSRX1 \regfile_contents_reg[43] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_238), .Q (regfile_contents[43]));
  DFFQSRX1 \regfile_contents_reg[7] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_241), .Q (regfile_contents[7]));
  DFFQSRX1 \regfile_contents_reg[13] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_240), .Q (regfile_contents[13]));
  DFFQSRX1 \regfile_contents_reg[37] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_244), .Q (regfile_contents[37]));
  DFFQSRX1 \regfile_contents_reg[31] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_242), .Q (regfile_contents[31]));
  MUX2X1 g3984__8246(.A (n_243), .B (regfile_contents[19]), .S (n_277),
       .Z (n_246));
  DFFQX1 \result_handler_Q_reg[5] (.CLK (n_245), .D (n_226), .Q
       (matrix_result[5]));
  DFFQX1 \result_handler_Q_reg[17] (.CLK (n_245), .D (n_228), .Q
       (matrix_result[17]));
  DFFQX1 \result_handler_Q_reg[23] (.CLK (n_245), .D (n_227), .Q
       (matrix_result[23]));
  MUX2X1 g3982__7098(.A (n_243), .B (regfile_contents[37]), .S (n_273),
       .Z (n_244));
  MUX2X1 g3983__6131(.A (n_243), .B (regfile_contents[31]), .S (n_283),
       .Z (n_242));
  MUX2X1 g3981__1881(.A (n_243), .B (regfile_contents[7]), .S (n_279),
       .Z (n_241));
  MUX2X1 g3992__5115(.A (n_243), .B (regfile_contents[13]), .S (n_275),
       .Z (n_240));
  MUX2X1 g3989__7482(.A (regfile_contents[25]), .B (n_243), .S (n_281),
       .Z (n_239));
  MUX2X1 g3990__4733(.A (regfile_contents[43]), .B (n_243), .S (n_288),
       .Z (n_238));
  MUX2X1 g3991__6161(.A (regfile_contents[1]), .B (n_243), .S (n_285),
       .Z (n_237));
  DFFQX1 \result_handler_Q_reg[11] (.CLK (n_245), .D (n_229), .Q
       (matrix_result[11]));
  AND2X1 g4007__9315(.A (n_235), .B (n_236), .Z (n_248));
  NOR2X1 g4008__9945(.A (n_236), .B (n_235), .Z (n_247));
  NOR2X1 g3987__2883(.A (n_234), .B (n_232), .Z (n_250));
  XOR2X1 g3985__2346(.A (n_230), .B (n_231), .Z (n_233));
  NOR2X1 g4016__1666(.A (n_211), .B (n_225), .Z (n_235));
  DFFQSRX1 \regfile_contents_reg[36] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_217), .Q (regfile_contents[36]));
  DFFQSRX1 \regfile_contents_reg[6] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_219), .Q (regfile_contents[6]));
  DFFQSRX1 \regfile_contents_reg[18] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_218), .Q (regfile_contents[18]));
  DFFQSRX1 \regfile_contents_reg[24] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_223), .Q (regfile_contents[24]));
  DFFQSRX1 \regfile_contents_reg[30] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_216), .Q (regfile_contents[30]));
  DFFQSRX1 \regfile_contents_reg[42] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_221), .Q (regfile_contents[42]));
  AND2X1 g4009__7410(.A (n_231), .B (n_230), .Z (n_232));
  XOR2X1 g3995__6417(.A (n_214), .B (n_24), .Z (n_229));
  XOR2X1 g3988__5477(.A (n_212), .B (n_26), .Z (n_228));
  XOR2X1 g3993__2398(.A (n_215), .B (n_25), .Z (n_227));
  XOR2X1 g3994__5107(.A (n_213), .B (n_6), .Z (n_226));
  DFFQSRX1 \regfile_contents_reg[0] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_220), .Q (regfile_contents[0]));
  DFFQSRX1 \regfile_contents_reg[12] (.SETB (n_300), .RESETB (1'b1),
       .CLK (clock), .D (n_224), .Q (regfile_contents[12]));
  NOR2X1 g4019__6260(.A (n_210), .B (n_234), .Z (n_243));
  AND2X1 g4037__4319(.A (n_230), .B (n_203), .Z (n_225));
  MUX2X1 g4021__8428(.A (n_222), .B (regfile_contents[12]), .S (n_275),
       .Z (n_224));
  MUX2X1 g4022__5526(.A (regfile_contents[24]), .B (n_222), .S (n_281),
       .Z (n_223));
  MUX2X1 g4023__6783(.A (regfile_contents[42]), .B (n_222), .S (n_288),
       .Z (n_221));
  MUX2X1 g4024__3680(.A (regfile_contents[0]), .B (n_222), .S (n_285),
       .Z (n_220));
  MUX2X1 g4020__1617(.A (n_222), .B (regfile_contents[6]), .S (n_279),
       .Z (n_219));
  XOR2X1 g4029__2802(.A (n_209), .B (n_208), .Z (n_231));
  MUX2X1 g4013__1705(.A (n_222), .B (regfile_contents[18]), .S (n_277),
       .Z (n_218));
  DFFQX1 \result_handler_Q_reg[4] (.CLK (n_245), .D (n_205), .Q
       (matrix_result[4]));
  DFFQX1 \result_handler_Q_reg[16] (.CLK (n_245), .D (n_207), .Q
       (matrix_result[16]));
  MUX2X1 g4011__5122(.A (n_222), .B (regfile_contents[36]), .S (n_273),
       .Z (n_217));
  MUX2X1 g4012__8246(.A (n_222), .B (regfile_contents[30]), .S (n_283),
       .Z (n_216));
  DFFQX1 \result_handler_Q_reg[22] (.CLK (n_245), .D (n_206), .Q
       (matrix_result[22]));
  DFFQX1 \result_handler_Q_reg[10] (.CLK (n_245), .D (n_204), .Q
       (matrix_result[10]));
  NAND2X1 g4017__7098(.A (n_201), .B (n_78), .Z (n_215));
  NAND2X1 g4015__6131(.A (n_195), .B (n_93), .Z (n_214));
  NAND2X1 g4014__1881(.A (n_197), .B (n_83), .Z (n_213));
  NAND2X1 g4018__5115(.A (n_199), .B (n_87), .Z (n_212));
  AND2X1 g4038__7482(.A (n_191), .B (n_190), .Z (n_211));
  AND2X1 g4034__4733(.A (n_193), .B (n_192), .Z (n_210));
  OR2X1 g4042__6161(.A (n_202), .B (n_230), .Z (n_261));
  NAND2X1 g4036__9315(.A (n_209), .B (n_208), .Z (n_236));
  AND2X1 g4043__9945(.A (n_230), .B (n_222), .Z (n_234));
  XOR2X1 g4025__2883(.A (n_198), .B (n_88), .Z (n_207));
  XOR2X1 g4026__2346(.A (n_200), .B (n_79), .Z (n_206));
  XOR2X1 g4027__1666(.A (n_196), .B (n_84), .Z (n_205));
  XOR2X1 g4028__7410(.A (n_194), .B (n_94), .Z (n_204));
  INVX2 g4053(.A (n_202), .Z (n_203));
  OR2X1 g4033__6417(.A (n_14), .B (n_200), .Z (n_201));
  OR2X1 g4039__5477(.A (n_36), .B (n_198), .Z (n_199));
  OR2X1 g4040__2398(.A (n_11), .B (n_196), .Z (n_197));
  OR2X1 g4041__5107(.A (n_16), .B (n_194), .Z (n_195));
  NAND2X1 g4044__6260(.A (element_A[1]), .B (element_B[0]), .Z (n_193));
  NAND2X1 g4045__4319(.A (element_A[0]), .B (element_B[1]), .Z (n_192));
  NAND2X1 g4056__8428(.A (element_A[2]), .B (element_B[1]), .Z (n_191));
  NAND2X1 g4055__5526(.A (element_A[1]), .B (element_B[2]), .Z (n_190));
  NAND2X1 g4046__6783(.A (element_A[2]), .B (element_B[0]), .Z (n_209));
  NAND2X1 g4060__3680(.A (element_A[2]), .B (element_B[2]), .Z (n_202));
  NAND2X1 g4048__1617(.A (element_A[0]), .B (element_B[2]), .Z (n_208));
  AND2X1 g4051__2802(.A (element_A[1]), .B (element_B[1]), .Z (n_230));
  AND2X1 g4052__1705(.A (element_A[0]), .B (element_B[0]), .Z (n_222));
  DFFQX1 \result_handler_Q_reg[3] (.CLK (n_245), .D (n_187), .Q
       (matrix_result[3]));
  DFFQX1 \fsm_current_state_reg[0] (.CLK (clock), .D (n_184), .Q
       (fsm_current_state[0]));
  DFFQX1 \result_handler_Q_reg[9] (.CLK (n_245), .D (n_186), .Q
       (matrix_result[9]));
  DFFQX1 \result_handler_Q_reg[21] (.CLK (n_245), .D (n_188), .Q
       (matrix_result[21]));
  DFFQX1 \result_handler_Q_reg[15] (.CLK (n_245), .D (n_185), .Q
       (matrix_result[15]));
  NOR2X1 g4047__5122(.A (n_64), .B (n_181), .Z (n_200));
  NOR2X1 g4049__8246(.A (n_68), .B (n_183), .Z (n_198));
  NOR2X1 g4061__7098(.A (n_62), .B (n_179), .Z (n_196));
  NOR2X1 g4062__6131(.A (n_75), .B (n_175), .Z (n_194));
  DFFQX1 \matb_element_reg[2] (.CLK (n_189), .D (n_177), .Q
       (element_B[2]));
  DFFQX1 \matb_element_reg[0] (.CLK (n_189), .D (n_176), .Q
       (element_B[0]));
  DFFQX1 \matb_element_reg[1] (.CLK (n_189), .D (n_173), .Q
       (element_B[1]));
  XOR2X1 g4058__1881(.A (n_180), .B (n_65), .Z (n_188));
  XOR2X1 g4057__5115(.A (n_178), .B (n_63), .Z (n_187));
  XOR2X1 g4054__7482(.A (n_174), .B (n_76), .Z (n_186));
  XOR2X1 g4059__4733(.A (n_182), .B (n_69), .Z (n_185));
  DFFQX1 \mata_element_reg[0] (.CLK (n_189), .D (n_170), .Q
       (element_A[0]));
  NOR2X1 g4071__6161(.A (reset), .B (n_167), .Z (n_184));
  DFFQX1 \statusREG_entry_out_reg[3] (.CLK (clock), .D (n_171), .Q
       (AB_entries[3]));
  DFFQX1 \mata_element_reg[1] (.CLK (n_189), .D (n_169), .Q
       (element_A[1]));
  DFFQX1 \mata_element_reg[2] (.CLK (n_189), .D (n_168), .Q
       (element_A[2]));
  DFFQX1 \fsm_current_state_reg[1] (.CLK (clock), .D (n_172), .Q
       (fsm_current_state[1]));
  AND2X1 g4075__9315(.A (n_182), .B (n_8), .Z (n_183));
  AND2X1 g4076__9945(.A (n_180), .B (n_31), .Z (n_181));
  AND2X1 g4077__2883(.A (n_178), .B (n_19), .Z (n_179));
  NAND3X1 g4096__2346(.A (n_166), .B (n_107), .C (n_124), .Z (n_177));
  NAND3X1 g4091__1666(.A (n_164), .B (n_101), .C (n_109), .Z (n_176));
  AND2X1 g4078__7410(.A (n_174), .B (n_28), .Z (n_175));
  NAND3X1 g4098__6417(.A (n_165), .B (n_108), .C (n_114), .Z (n_173));
  NAND2X1 g4085__5477(.A (n_156), .B (n_50), .Z (n_172));
  AND2X1 g4084__2398(.A (n_158), .B (n_146), .Z (n_171));
  NAND3X1 g4093__5107(.A (n_159), .B (n_105), .C (n_97), .Z (n_170));
  DFFQX1 \result_handler_Q_reg[20] (.CLK (n_245), .D (n_163), .Q
       (matrix_result[20]));
  DFFQX1 \result_handler_Q_reg[2] (.CLK (n_245), .D (n_160), .Q
       (matrix_result[2]));
  DFFQX1 \result_handler_Q_reg[8] (.CLK (n_245), .D (n_162), .Q
       (matrix_result[8]));
  DFFQX1 \result_handler_Q_reg[14] (.CLK (n_245), .D (n_161), .Q
       (matrix_result[14]));
  NAND3X1 g4094__6260(.A (n_157), .B (n_103), .C (n_96), .Z (n_169));
  NAND3X1 g4095__4319(.A (n_153), .B (n_102), .C (n_100), .Z (n_168));
  NOR2X1 g4097__8428(.A (n_72), .B (n_154), .Z (n_167));
  NAND2X1 g4087__5526(.A (n_145), .B (n_89), .Z (n_182));
  NAND2X1 g4086__6783(.A (n_141), .B (n_81), .Z (n_178));
  NAND2X1 g4088__3680(.A (n_151), .B (n_85), .Z (n_180));
  DFFQX1 \statusREG_entry_out_reg[1] (.CLK (clock), .D (n_139), .Q
       (AB_entries[1]));
  AND2X1 g4104__1617(.A (n_128), .B (n_143), .Z (n_166));
  AND2X1 g4121__2802(.A (n_123), .B (n_138), .Z (n_165));
  AND2X1 g4120__1705(.A (n_115), .B (n_152), .Z (n_164));
  NAND2X1 g4102__5122(.A (n_149), .B (n_91), .Z (n_174));
  DFFQX1 \statusREG_entry_out_reg[2] (.CLK (clock), .D (n_147), .Q
       (AB_entries[2]));
  XOR2X1 g4100__8246(.A (n_150), .B (n_86), .Z (n_163));
  DFFQX1 \result_handler_Q_reg[1] (.CLK (n_245), .D (n_136), .Q
       (matrix_result[1]));
  XOR2X1 g4092__7098(.A (n_148), .B (n_92), .Z (n_162));
  XOR2X1 g4099__6131(.A (n_144), .B (n_90), .Z (n_161));
  DFFQX1 \result_handler_Q_reg[7] (.CLK (n_245), .D (n_129), .Q
       (matrix_result[7]));
  DFFQX1 \result_handler_Q_reg[13] (.CLK (n_245), .D (n_133), .Q
       (matrix_result[13]));
  DFFQX1 \result_handler_Q_reg[19] (.CLK (n_245), .D (n_132), .Q
       (matrix_result[19]));
  DFFQSRX1 \result_handler_address_reg[3] (.SETB (n_300), .RESETB
       (1'b1), .CLK (n_245), .D (n_134), .Q (matrix_count[3]));
  DFFQX1 \statusREG_entry_out_reg[0] (.CLK (clock), .D (n_122), .Q
       (AB_entries[0]));
  XOR2X1 g4101__1881(.A (n_140), .B (n_82), .Z (n_160));
  AND2X1 g4105__5115(.A (n_127), .B (n_112), .Z (n_159));
  NAND2X1 g4108__7482(.A (n_155), .B (n_98), .Z (n_158));
  AND2X1 g4123__4733(.A (n_131), .B (n_110), .Z (n_157));
  OR2X1 g4122__6161(.A (n_121), .B (n_155), .Z (n_156));
  AND2X1 g4118__9315(.A (n_155), .B (n_137), .Z (n_154));
  AND2X1 g4119__9945(.A (n_135), .B (n_120), .Z (n_153));
  NAND2X1 g4117__2883(.A (n_119), .B (AB_entries[1]), .Z (n_273));
  NOR2X1 g4132__2346(.A (n_40), .B (n_155), .Z (n_288));
  NAND2X1 g4112__1666(.A (n_117), .B (AB_entries[1]), .Z (n_275));
  NAND2X1 g4170__7410(.A (n_142), .B (matrix_B[6]), .Z (n_152));
  OR2X1 g4103__6417(.A (n_33), .B (n_150), .Z (n_151));
  OR2X1 g4106__5477(.A (n_20), .B (n_148), .Z (n_149));
  AND2X1 g4107__2398(.A (n_146), .B (n_95), .Z (n_147));
  OR2X1 g4109__5107(.A (n_22), .B (n_144), .Z (n_145));
  NOR2X1 g4115__6260(.A (AB_entries[1]), .B (n_116), .Z (n_285));
  NAND2X1 g4161__4319(.A (n_142), .B (matrix_B[8]), .Z (n_143));
  OR2X1 g4124__8428(.A (n_9), .B (n_140), .Z (n_141));
  AND2X1 g4158__5526(.A (n_146), .B (n_5), .Z (n_139));
  NAND2X1 g4157__6783(.A (n_142), .B (matrix_B[7]), .Z (n_138));
  NAND3X1 g4131__3680(.A (n_142), .B (n_137), .C (n_125), .Z (n_279));
  NOR2X1 g4116__1617(.A (AB_entries[1]), .B (n_118), .Z (n_281));
  NAND3X1 g4130__2802(.A (n_142), .B (n_137), .C (AB_entries[2]), .Z
       (n_283));
  XOR2X1 g4128__1705(.A (n_51), .B (n_58), .Z (n_136));
  NAND2X1 g4144__5122(.A (n_130), .B (matrix_A[11]), .Z (n_135));
  XOR2X1 g4125__8246(.A (matrix_count[3]), .B (n_61), .Z (n_134));
  XOR2X1 g4126__7098(.A (n_44), .B (n_48), .Z (n_133));
  XOR2X1 g4127__6131(.A (n_66), .B (n_43), .Z (n_132));
  NAND2X1 g4142__1881(.A (n_130), .B (matrix_A[10]), .Z (n_131));
  XOR2X1 g4129__5115(.A (n_54), .B (n_71), .Z (n_129));
  NAND2X1 g4137__7482(.A (n_126), .B (matrix_B[11]), .Z (n_128));
  NAND2X1 g4140__4733(.A (n_130), .B (matrix_A[9]), .Z (n_127));
  DFFQSRX1 \result_handler_address_reg[2] (.SETB (n_300), .RESETB
       (1'b1), .CLK (n_245), .D (n_80), .Q (matrix_count[2]));
  NAND3X1 g4114__6161(.A (n_126), .B (n_137), .C (n_125), .Z (n_277));
  NAND2X1 g4156__9315(.A (n_113), .B (matrix_B[2]), .Z (n_124));
  NAND2X1 g4147__9945(.A (n_126), .B (matrix_B[10]), .Z (n_123));
  NOR2X1 g4149__2883(.A (AB_entries[0]), .B (n_121), .Z (n_122));
  NAND2X1 g4168__2346(.A (n_111), .B (matrix_A[5]), .Z (n_120));
  INVX2 g4153(.A (n_118), .Z (n_119));
  INVX2 g4154(.A (n_116), .Z (n_117));
  NAND2X1 g4146__1666(.A (n_126), .B (matrix_B[9]), .Z (n_115));
  NAND2X1 g4160__7410(.A (n_113), .B (matrix_B[1]), .Z (n_114));
  NAND2X1 g4163__6417(.A (n_111), .B (matrix_A[3]), .Z (n_112));
  NAND2X1 g4165__5477(.A (n_111), .B (matrix_A[4]), .Z (n_110));
  NAND2X1 g4167__2398(.A (n_113), .B (matrix_B[0]), .Z (n_109));
  NAND2X1 g4152__5107(.A (n_130), .B (AB_entries[1]), .Z (n_155));
  NAND2X1 g4138__6260(.A (n_106), .B (matrix_B[4]), .Z (n_108));
  NAND2X1 g4172__4319(.A (n_99), .B (n_137), .Z (n_116));
  NOR2X1 g4175__8428(.A (n_57), .B (n_53), .Z (n_140));
  NOR2X1 g4174__5526(.A (n_41), .B (n_67), .Z (n_150));
  NOR2X1 g4173__6783(.A (n_70), .B (n_56), .Z (n_148));
  NAND2X1 g4171__3680(.A (n_104), .B (n_137), .Z (n_118));
  DFFQSRX1 \result_handler_address_reg[1] (.SETB (n_300), .RESETB
       (1'b1), .CLK (n_245), .D (n_49), .Q (matrix_count[1]));
  INVX2 g4198(.A (n_121), .Z (n_146));
  NOR2X1 g4197__1617(.A (AB_entries[1]), .B (n_39), .Z (n_142));
  NAND2X1 g4139__2802(.A (n_106), .B (matrix_B[5]), .Z (n_107));
  NAND2X1 g4141__1705(.A (n_104), .B (matrix_A[6]), .Z (n_105));
  NAND2X1 g4143__5122(.A (n_104), .B (matrix_A[7]), .Z (n_103));
  NAND2X1 g4145__8246(.A (n_104), .B (matrix_A[8]), .Z (n_102));
  NAND2X1 g4148__7098(.A (n_106), .B (matrix_B[3]), .Z (n_101));
  NAND2X1 g4169__6131(.A (n_99), .B (matrix_A[2]), .Z (n_100));
  NAND2X1 g4162__1881(.A (n_74), .B (AB_entries[3]), .Z (n_98));
  NAND2X1 g4164__5115(.A (n_99), .B (matrix_A[0]), .Z (n_97));
  NAND2X1 g4166__7482(.A (n_99), .B (matrix_A[1]), .Z (n_96));
  NOR2X1 g4150__4733(.A (n_47), .B (n_46), .Z (n_144));
  XOR2X1 g4155__6161(.A (n_73), .B (n_125), .Z (n_95));
  NAND2X1 g4180__9315(.A (n_17), .B (n_93), .Z (n_94));
  NAND2X1 g4181__9945(.A (n_21), .B (n_91), .Z (n_92));
  NAND2X1 g4183__2883(.A (n_23), .B (n_89), .Z (n_90));
  NAND2X1 g4186__2346(.A (n_37), .B (n_87), .Z (n_88));
  NAND2X1 g4188__1666(.A (n_34), .B (n_85), .Z (n_86));
  NAND2X1 g4179__7410(.A (n_12), .B (n_83), .Z (n_84));
  NOR2X1 g4192__6417(.A (AB_entries[1]), .B (n_29), .Z (n_113));
  AND2X1 g4191__5477(.A (n_77), .B (n_125), .Z (n_111));
  DFFQX1 \result_handler_Q_reg[12] (.CLK (n_245), .D (n_35), .Q
       (matrix_result[12]));
  NAND2X1 g4213__2398(.A (n_10), .B (n_81), .Z (n_82));
  XOR2X1 g4159__5107(.A (matrix_count[2]), .B (n_60), .Z (n_80));
  DFFQX1 \result_handler_Q_reg[6] (.CLK (n_245), .D (n_32), .Q
       (matrix_result[6]));
  NAND2X1 g4212__6260(.A (n_15), .B (n_78), .Z (n_79));
  DFFQX1 \result_handler_Q_reg[0] (.CLK (n_245), .D (n_38), .Q
       (matrix_result[0]));
  DFFQX1 \result_handler_Q_reg[18] (.CLK (n_245), .D (n_13), .Q
       (matrix_result[18]));
  NAND2X1 g4220__4319(.A (n_137), .B (n_300), .Z (n_121));
  AND2X1 g4196__8428(.A (n_77), .B (AB_entries[2]), .Z (n_130));
  AND2X1 g4219__5526(.A (n_77), .B (AB_entries[1]), .Z (n_126));
  NOR2X1 g4185__6783(.A (n_75), .B (n_27), .Z (n_76));
  OR2X1 g4177__3680(.A (n_125), .B (n_73), .Z (n_74));
  NOR2X1 g4178__1617(.A (fsm_current_state[0]), .B (n_2), .Z (n_72));
  OR2X1 g4182__2802(.A (n_70), .B (n_55), .Z (n_71));
  NOR2X1 g4184__1705(.A (n_68), .B (n_7), .Z (n_69));
  NOR2X1 g4176__5122(.A (n_42), .B (n_66), .Z (n_67));
  NOR2X1 g4187__8246(.A (n_30), .B (n_64), .Z (n_65));
  NOR2X1 g4189__7098(.A (n_18), .B (n_62), .Z (n_63));
  AND2X1 g4190__6131(.A (n_60), .B (matrix_count[2]), .Z (n_61));
  AND2X1 g4195__1881(.A (n_59), .B (AB_entries[2]), .Z (n_104));
  AND2X1 g4193__5115(.A (n_59), .B (n_125), .Z (n_99));
  OR2X1 g4211__7482(.A (n_52), .B (n_57), .Z (n_58));
  NOR2X1 g4201__4733(.A (n_55), .B (n_54), .Z (n_56));
  NOR2X1 g4202__6161(.A (n_52), .B (n_51), .Z (n_53));
  NAND3X1 g4204__9315(.A (n_4), .B (fsm_current_state[1]), .C (n_300),
       .Z (n_50));
  NOR2X1 g4208__9945(.A (n_3), .B (n_60), .Z (n_49));
  OR2X1 g4210__2883(.A (n_47), .B (n_45), .Z (n_48));
  NOR2X1 g4200__2346(.A (n_45), .B (n_44), .Z (n_46));
  OR2X1 g4215__1666(.A (n_42), .B (n_41), .Z (n_43));
  INVX2 g4227(.A (n_137), .Z (n_40));
  INVX2 g4226(.A (n_77), .Z (n_39));
  AND2X1 g4218__7410(.A (n_59), .B (AB_entries[1]), .Z (n_106));
  DFFQSRX1 \result_handler_address_reg[0] (.SETB (n_300), .RESETB
       (1'b1), .CLK (n_245), .D (n_1), .Q (matrix_count[0]));
  XOR2X1 g4206__6417(.A (regfile_contents[6]), .B
       (regfile_contents[0]), .Z (n_38));
  INVX1 g4256(.A (n_36), .Z (n_37));
  XOR2X1 g4199__5477(.A (regfile_contents[24]), .B
       (regfile_contents[30]), .Z (n_35));
  INVX1 g4255(.A (n_33), .Z (n_34));
  XOR2X1 g4205__2398(.A (regfile_contents[12]), .B
       (regfile_contents[18]), .Z (n_32));
  INVX1 g4253(.A (n_30), .Z (n_31));
  INVX2 g4257(.A (n_59), .Z (n_29));
  INVX1 g4251(.A (n_27), .Z (n_28));
  XOR2X1 g4209__5107(.A (regfile_contents[29]), .B
       (regfile_contents[35]), .Z (n_26));
  XOR2X1 g4216__6260(.A (regfile_contents[41]), .B
       (regfile_contents[47]), .Z (n_25));
  XOR2X1 g4217__4319(.A (regfile_contents[17]), .B
       (regfile_contents[23]), .Z (n_24));
  INVX1 g4225(.A (n_22), .Z (n_23));
  INVX1 g4224(.A (n_20), .Z (n_21));
  INVX1 g4222(.A (n_18), .Z (n_19));
  INVX1 g4223(.A (n_16), .Z (n_17));
  INVX1 g4254(.A (n_14), .Z (n_15));
  XOR2X1 g4207__8428(.A (regfile_contents[36]), .B
       (regfile_contents[42]), .Z (n_13));
  INVX1 g4250(.A (n_11), .Z (n_12));
  INVX1 g4221(.A (n_9), .Z (n_10));
  INVX1 g4252(.A (n_7), .Z (n_8));
  XOR2X1 g4214__5526(.A (regfile_contents[11]), .B
       (regfile_contents[5]), .Z (n_6));
  XOR2X1 g4203__6783(.A (AB_entries[1]), .B (AB_entries[0]), .Z (n_5));
  NOR2X1 g4246__3680(.A (n_0), .B (AB_entries[3]), .Z (n_77));
  NOR2X1 g4249__1617(.A (fsm_current_state[1]), .B (n_4), .Z (n_137));
  NOR2X1 g4229__2802(.A (matrix_count[1]), .B (matrix_count[0]), .Z
       (n_3));
  AND2X1 g4262__1705(.A (regfile_contents[15]), .B
       (regfile_contents[21]), .Z (n_75));
  NOR2X1 g4258__5122(.A (regfile_contents[10]), .B
       (regfile_contents[4]), .Z (n_11));
  NOR2X1 g4268__8246(.A (regfile_contents[38]), .B
       (regfile_contents[44]), .Z (n_33));
  NAND2X1 g4239__7098(.A (regfile_contents[14]), .B
       (regfile_contents[20]), .Z (n_91));
  NAND2X1 g4270__6131(.A (regfile_contents[44]), .B
       (regfile_contents[38]), .Z (n_85));
  AND2X1 g4269__1881(.A (regfile_contents[43]), .B
       (regfile_contents[37]), .Z (n_41));
  NOR2X1 g4272__5115(.A (regfile_contents[34]), .B
       (regfile_contents[28]), .Z (n_36));
  AND2X1 g4274__7482(.A (regfile_contents[25]), .B
       (regfile_contents[31]), .Z (n_47));
  NOR2X1 g4244__4733(.A (regfile_contents[32]), .B
       (regfile_contents[26]), .Z (n_22));
  NOR2X1 g4260__6161(.A (regfile_contents[21]), .B
       (regfile_contents[15]), .Z (n_27));
  NOR2X1 g4237__9315(.A (regfile_contents[22]), .B
       (regfile_contents[16]), .Z (n_16));
  NOR2X1 g4265__9945(.A (regfile_contents[33]), .B
       (regfile_contents[27]), .Z (n_7));
  AND2X1 g4273__2883(.A (regfile_contents[45]), .B
       (regfile_contents[39]), .Z (n_64));
  NAND2X1 g4247__2346(.A (regfile_contents[42]), .B
       (regfile_contents[36]), .Z (n_66));
  NAND2X1 g4271__1666(.A (regfile_contents[26]), .B
       (regfile_contents[32]), .Z (n_89));
  AND2X1 g4234__7410(.A (regfile_contents[3]), .B
       (regfile_contents[9]), .Z (n_62));
  NOR2X1 g4230__6417(.A (regfile_contents[8]), .B
       (regfile_contents[2]), .Z (n_9));
  NOR2X1 g4231__5477(.A (regfile_contents[19]), .B
       (regfile_contents[13]), .Z (n_55));
  NAND2X1 g4232__2398(.A (regfile_contents[46]), .B
       (regfile_contents[40]), .Z (n_78));
  AND2X1 g4279__5107(.A (fsm_current_state[1]), .B
       (fsm_current_state[0]), .Z (n_245));
  NOR2X1 g4228__6260(.A (start), .B (fsm_current_state[1]), .Z (n_2));
  NOR2X1 g4236__4319(.A (regfile_contents[9]), .B
       (regfile_contents[3]), .Z (n_18));
  AND2X1 g4242__8428(.A (regfile_contents[1]), .B
       (regfile_contents[7]), .Z (n_57));
  NAND2X1 g4245__5526(.A (AB_entries[1]), .B (AB_entries[0]), .Z
       (n_73));
  AND2X1 g4238__6783(.A (regfile_contents[27]), .B
       (regfile_contents[33]), .Z (n_68));
  NOR2X1 g4240__3680(.A (regfile_contents[20]), .B
       (regfile_contents[14]), .Z (n_20));
  NOR2X1 g4243__1617(.A (regfile_contents[37]), .B
       (regfile_contents[43]), .Z (n_42));
  NOR2X1 g4264__2802(.A (regfile_contents[31]), .B
       (regfile_contents[25]), .Z (n_45));
  NOR2X1 g4266__1705(.A (regfile_contents[39]), .B
       (regfile_contents[45]), .Z (n_30));
  NAND2X1 g4276__5122(.A (regfile_contents[24]), .B
       (regfile_contents[30]), .Z (n_44));
  NAND2X1 g4248__8246(.A (regfile_contents[12]), .B
       (regfile_contents[18]), .Z (n_54));
  NAND2X1 g4241__7098(.A (regfile_contents[28]), .B
       (regfile_contents[34]), .Z (n_87));
  NOR2X1 g4235__6131(.A (regfile_contents[7]), .B
       (regfile_contents[1]), .Z (n_52));
  NAND2X1 g4233__1881(.A (regfile_contents[4]), .B
       (regfile_contents[10]), .Z (n_83));
  NAND2X1 g4277__5115(.A (regfile_contents[0]), .B
       (regfile_contents[6]), .Z (n_51));
  AND2X1 g4261__7482(.A (regfile_contents[13]), .B
       (regfile_contents[19]), .Z (n_70));
  NAND2X1 g4263__4733(.A (regfile_contents[2]), .B
       (regfile_contents[8]), .Z (n_81));
  NOR2X1 g4267__6161(.A (regfile_contents[40]), .B
       (regfile_contents[46]), .Z (n_14));
  NAND2X1 g4259__9315(.A (regfile_contents[16]), .B
       (regfile_contents[22]), .Z (n_93));
  AND2X1 g4275__9945(.A (matrix_count[0]), .B (matrix_count[1]), .Z
       (n_60));
  NOR2X1 g4278__2883(.A (AB_entries[3]), .B (AB_entries[0]), .Z (n_59));
  INVX2 g4281(.A (fsm_current_state[0]), .Z (n_4));
  INVX2 g4283(.A (AB_entries[2]), .Z (n_125));
  INVX1 g4284(.A (reset), .Z (n_300));
  INVX1 g4280(.A (matrix_count[0]), .Z (n_1));
  INVX2 g4282(.A (AB_entries[0]), .Z (n_0));
  INVX1 g4285(.A (clock), .Z (n_189));
endmodule

